repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v3.0.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
    - id: black
      language_version: python3

- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.35.0
  hooks:
    - id: terraform_fmt

- repo: git://github.com/markdownlint/markdownlint
  rev: v0.11.0
  hooks:
    - id: markdownlint 
